"""add missing sqlQuery column to alert_rules

Revision ID: 1b64d9695755
Revises: e35d4db01ac2
Create Date: 2025-08-27 16:41:43.009978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b64d9695755'
down_revision = 'e35d4db01ac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('sqlQuery', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'sqlQuery')
    # ### end Alembic commands ###
