"""add keycloak_id to users table

Revision ID: 5b7ab65a1fe2
Revises: 1b64d9695755
Create Date: 2025-09-22 14:28:06.742482

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5b7ab65a1fe2'
down_revision = '1b64d9695755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['keycloak_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'keycloak_id')
    # ### end Alembic commands ###
