"""description

Revision ID: e35d4db01ac2
Revises: ac92703bd365
Create Date: 2025-08-13 09:53:15.786387

"""

# revision identifiers, used by Alembic.
revision = 'e35d4db01ac2'
down_revision = 'ac92703bd365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
