"""empty message

Revision ID: eb7dc605eb0f
Revises: 1b64d9695755
Create Date: 2025-09-19 09:50:45.699284

"""

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb7dc605eb0f'
down_revision = '1b64d9695755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'merchant_category_embeddings',
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('embedding', Vector(1536), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('category'),
    )
    op.create_table(
        'merchant_category_synonyms',
        sa.Column('synonym', sa.String(), nullable=False),
        sa.Column('canonical_category', sa.String(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('synonym'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_category_synonyms')
    op.drop_table('merchant_category_embeddings')
    # ### end Alembic commands ###
