// This file is auto-generated by @tanstack/router-vite-plugin
// It will be replaced during the build process

import type { AnyRoute } from '@tanstack/react-router'

export const routeTree: AnyRoute = {} as any
