{{- if .Values.routes.enabled -}}
{{- if .Values.nginx.enabled -}}
# Nginx Route - single entry point for both UI and API
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.nginx.name }}-route
  labels:
    {{- include "spending-monitor.nginx.labels" . | nindent 4 }}
  {{- with .Values.routes.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.routes.nginx.host }}
  host: {{ .Values.routes.nginx.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.nginx.name }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.routes.nginx.tls.enabled }}
  tls:
    termination: {{ .Values.routes.nginx.tls.termination | default "edge" }}
    {{- if .Values.routes.nginx.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.routes.nginx.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- else -}}
# UI Route (fallback when nginx is disabled)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.ui.name }}-route
  labels:
    {{- include "spending-monitor.ui.labels" . | nindent 4 }}
  {{- with .Values.routes.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.routes.ui.host }}
  host: {{ .Values.routes.ui.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.ui.name }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.routes.ui.tls.enabled }}
  tls:
    termination: {{ .Values.routes.ui.tls.termination | default "edge" }}
    {{- if .Values.routes.ui.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.routes.ui.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None

---
# API Route - serve API under /api path with rewrite (fallback when nginx is disabled)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.ui.name }}-api-route
  labels:
    {{- include "spending-monitor.ui.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  {{- with .Values.routes.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.routes.api.host }}
  host: {{ .Values.routes.api.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.api.name }}
    weight: 100
  port:
    targetPort: http
  path: /api
  {{- if .Values.routes.ui.tls.enabled }}
  tls:
    termination: {{ .Values.routes.ui.tls.termination | default "edge" }}
    {{- if .Values.routes.ui.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.routes.ui.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end -}}
{{- end }}