{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  labels:
    {{- include "spending-monitor.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "spending-monitor.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spending-monitor.ui.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "spending-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "spending-monitor.image" (dict "name" .Values.ui.image.repository "tag" .Values.ui.image.tag "Values" .Values) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $value := .Values.ui.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.ui.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.ui.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.ui.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ui.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.ui.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.healthCheck.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}